apiVersion: v1
kind: ConfigMap
metadata:
  name: sccstore-qcomplaints-config
data:
  # property-like keys; each key maps to a simple value
  SCC_DB_HOST: pg-service.sccstore-dev.svc.clusterset.local
  SCC_DB_NAME: sccstore
